### Get projects
GET https://api.braintrust.dev/v1/project
Authorization: Bearer sk-LHf9FSljJRXuba15Gl9y0XE07b0andBSu0OJYPgKarMz1mA8

### Get logs
POST https://api.braintrust.dev/v1/project_logs/1c2c6025-edae-4bb4-80cb-d2800c042826/fetch
Authorization: Bearer sk-LHf9FSljJRXuba15Gl9y0XE07b0andBSu0OJYPgKarMz1mA8
Content-Type: application/json

# {
#   "filters": [
#       {
#         "type": "path_lookup",
#         "path": [
#           "is_root"
#         ],
#         "value": true
#       }
#     ]
# }

###
POST https://api.braintrust.dev/btql
Authorization: Bearer sk-LHf9FSljJRXuba15Gl9y0XE07b0andBSu0OJYPgKarMz1mA8
Content-Type: application/json

{
  "query": "select: * | from: project_logs('1c2c6025-edae-4bb4-80cb-d2800c042826') | filter: is_root = true and tags includes 'annotate'"
}
