
### [PROD] Test latency
POST https://search.proem.ai/api/v1/latency/edge HTTP/1.1
content-type: application/json

{
  "foo": "bar"
}

### Log output: [0] api/v1/latency

### test runs:
### 1. 1124ms
### 2.  278ms
### 3.  240ms
### 4.  233ms
### 5.  258ms
### 6.  280ms
