import { createEnv } from "@t3-oss/env-nextjs";
import { vercel } from "@t3-oss/env-nextjs/presets";
import { z } from "zod";

export const env = createEnv({
	server: {
		ANTHROPIC_API_KEY: z.string(),
		CLERK_SECRET_KEY: z.string(),
		DATABASE_URL: z.string(),
		GOOGLE_VERTEX_CLIENT_EMAIL: z.string(),
		GOOGLE_VERTEX_LOCATION: z.string(),
		GOOGLE_VERTEX_PRIVATE_KEY: z.string(),
		GOOGLE_VERTEX_PROJECT: z.string(),
		INNGEST_EVENT_KEY: z.string(),
		INNGEST_SIGNING_KEY: z.string(),
		LANGCHAIN_API_KEY: z.string(),
		LANGCHAIN_ENDPOINT: z.string(),
		LANGCHAIN_PROJECT: z.string(),
		LANGCHAIN_TEST_API_KEY: z.string(),
		LANGCHAIN_TRACING_V2: z.string(),
		OPENAI_API_KEY_TEST: z.string().optional(), // This is only used for evaluation but the code is build and running in production
		OPENAI_API_KEY: z.string(),
		OPENALEX_API_KEY: z.string(),
		RATE_LIMITER_ENDPOINT: z.string(),
		RATE_LIMITER_PASSWORD: z.string(),
		REDIS_PAPERS_TOKEN: z.string(),
		REDIS_PAPERS_URL: z.string(),
		SENTRY_AUTH_TOKEN: z.string(),
		SENTRY_ORG: z.string(),
	},
	extends: [vercel()],
	isServer: typeof window === "undefined",
	experimental__runtimeEnv: {
		ANTHROPIC_API_KEY: process.env.ANTHROPIC_API_KEY,
		CLERK_SECRET_KEY: process.env.CLERK_SECRET_KEY,
		DATABASE_URL: process.env.DATABASE_URL,
		GOOGLE_VERTEX_CLIENT_EMAIL: process.env.GOOGLE_VERTEX_CLIENT_EMAIL,
		GOOGLE_VERTEX_LOCATION: process.env.GOOGLE_VERTEX_LOCATION,
		GOOGLE_VERTEX_PRIVATE_KEY: process.env.GOOGLE_VERTEX_PRIVATE_KEY,
		GOOGLE_VERTEX_PROJECT: process.env.GOOGLE_VERTEX_PROJECT,
		INNGEST_EVENT_KEY: process.env.INNGEST_EVENT_KEY,
		INNGEST_SIGNING_KEY: process.env.INNGEST_SIGNING_KEY,
		LANGCHAIN_API_KEY: process.env.LANGCHAIN_API_KEY,
		LANGCHAIN_ENDPOINT: process.env.LANGCHAIN_ENDPOINT,
		LANGCHAIN_PROJECT: process.env.LANGCHAIN_PROJECT,
		LANGCHAIN_TEST_API_KEY: process.env.LANGCHAIN_TEST_API_KEY,
		LANGCHAIN_TRACING_V2: process.env.LANGCHAIN_TRACING_V2,
		OPENAI_API_KEY_TEST: process.env.OPENAI_API_KEY_TEST,
		OPENAI_API_KEY: process.env.OPENAI_API_KEY,
		OPENALEX_API_KEY: process.env.OPENALEX_API_KEY,
		RATE_LIMITER_ENDPOINT: process.env.RATE_LIMITER_ENDPOINT,
		RATE_LIMITER_PASSWORD: process.env.RATE_LIMITER_PASSWORD,
		REDIS_PAPERS_TOKEN: process.env.REDIS_PAPERS_TOKEN,
		REDIS_PAPERS_URL: process.env.REDIS_PAPERS_URL,
		SENTRY_AUTH_TOKEN: process.env.SENTRY_AUTH_TOKEN,
		SENTRY_ORG: process.env.SENTRY_ORG,
	},
});
