export type Intent =
	| "ANSWER_EVERYDAY_QUESTION"
	| "ANSWER_FOLLOWUP_QUESTION"
	| "EXPLAIN_CONCEPT"
	| "FIND_PAPER"
	| "FIND_LATEST_PAPERS"
	| "FIND_INFLUENTIAL_PAPERS"
	| "FIND_PAPERS_BY_AUTHOR"
	| "FIND_PAPERS_CITING_A_GIVEN_PAPER"
	| "UNKNOWN";
