
### [DEV] Search OpenAlex
POST http://localhost:8000/api/v1/search HTTP/1.1
content-type: application/json

{
    "q": "Chain of Density"
}

### [DEV] Search OpenAlex with includes
POST http://localhost:8000/api/v1/search/edge HTTP/1.1
content-type: application/json

{
  "q": "Chain of Density",
  "includes": ["$.id", "$.publication_year", "$.type", "$.primary_location.source.display_name"]
}

### [DEV] Search OpenAlex with filter
POST http://localhost:8000/api/v1/search/edge HTTP/1.1
content-type: application/json

{
  "q": "alcohol risk thrombus",
  "includes": ["$.publication_date", "$.open_access.is_oa"],
  "filter": ["is_oa:false","publication_date:>2022-01-16", "publication_date:<2023-11-16"]
}

### [PROD] Search OpenAlex
POST https://search.proem.ai/api/v1/search HTTP/1.1
content-type: application/json

{
  "q": "effect of limited alcohol consumption on thrombus risk"
}
