
### [DEV] Search OpenAlex
POST http://localhost:8000/api/v1/search HTTP/1.1
content-type: application/json

{
  "q": "Chain of Density"
}

### [DEV] Search OpenAlex, returning some fields
POST http://localhost:8000/api/v1/search HTTP/1.1
content-type: application/json

{
  "q": "Chain of Density",
  "count": 10,
  "includes": ["concepts", "ids"]
}

### [DEV] Search OpenAlex, returning raw OA results
POST http://localhost:8000/api/v1/search HTTP/1.1
content-type: application/json

{
  "q": "Chain of Density",
  "count": 10,
  "includes": ["raw"]
}

### [PROD] Search OpenAlex
POST https://search.proem.ai/api/v1/search HTTP/1.1
content-type: application/json

{
  "q": "Chain of Density"
}
