export const metadata = {
  title: "Terms of Service for Proem",
  // description: "Generated by create next app",
};

export default function TermsPage() {
  return (
    <div className="flex flex-col items-center justify-between min-h-screen p-24">
      <div className="relative flex flex-col place-items-center before:absolute before:h-[300px] before:w-[480px] before:-translate-x-1/2">
        <div>
          <h1>Proemial Foundation Terms of Service</h1>

          <h2>Introduction</h2>
          <p>
            Welcome to Proem! By using our services, you agree to these Terms of
            Service (ToS).
          </p>

          <h2>Accessing Our Services</h2>
          <p>
            While unregistered users can browse freely without any data logging,
            registered users can contribute by commenting on preprints.
            Registering requires providing a valid email address and creating a
            password.
          </p>

          <h2>Use of Services</h2>
          <p>
            As a user, you agree to use our services respectfully and
            responsibly, refraining from any behavior that infringes upon the
            rights of others or violates applicable laws.
          </p>

          <h2>Data</h2>
          <p>
            Registered users&apos; activities, comments, and posted content will
            be logged and stored on a public blockchain, becoming part of the
            Commons. However, we will not share sensitive information without
            your consent.
          </p>

          <h2>Intellectual Property</h2>
          <p>
            Content on Proem is published under Creative Commons licenses. You
            agree to respect these licenses when using or distributing the
            content.
          </p>

          <h2>Changes to Terms of Service</h2>
          <p>
            We reserve the right to modify these ToS. Any changes will be posted
            on this page.
          </p>

          <h2>Contact Us</h2>
          <p>
            If you have any questions about these terms, please contact us at{" "}
            <a href="mailto:hi@proem.ai">hi@proem.ai</a>.
          </p>

          <p>Thank you for contributing to the Commons through Proem!</p>

          <p className="mt-4 italic text-right">
            Last updated: 17th July, 2023.
          </p>
        </div>
      </div>
    </div>
  );
}
