import { fetchSummary } from "@/app/(pages)/(app)/paper/oa/[id]/fetch-summary";
import { use } from "react";
import Markdown from "react-markdown";

export function Summary(...args: Parameters<typeof fetchSummary>) {
	// const headline = use(fetchSummary(...args));

	// TODO!: fetch from clientside
	return <Markdown>{"autogenerated headline comming"}</Markdown>;
}
